
-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Expense Records
create table if not exists expense_records (
  id bigint generated by default as identity primary key,
  project text,
  category text not null,
  sub_category text,
  amount numeric(10, 2) not null,
  expense_date date not null,
  description text,
  voice_text text,
  member_id bigint,
  import_id bigint,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Expense Categories
create table if not exists expense_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text,
  color text default '#10B981',
  parent_id bigint,
  level integer default 2,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Monthly Budgets
create table if not exists monthly_budgets (
  id bigint generated by default as identity primary key,
  project text,
  category text not null,
  sub_category text,
  budget_amount numeric(10, 2) not null,
  year integer not null,
  month integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(project, category, sub_category, year, month)
);

-- 4. Year Goals
create table if not exists year_goals (
  id bigint generated by default as identity primary key,
  year integer not null,
  project text default '',
  category text default '',
  sub_category text default '',
  goal_amount numeric(10, 2) not null,
  expense_type text default '常规费用',
  member_id bigint default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(year, project, category, sub_category, member_id)
);

-- 5. Expense Hierarchy
create table if not exists expense_hierarchy (
  id bigint generated by default as identity primary key,
  project text,
  category text,
  sub_category text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(project, category, sub_category)
);

-- 6. Families
create table if not exists families (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 7. Members
create table if not exists members (
  id bigint generated by default as identity primary key,
  name text not null,
  family_id bigint references families(id) on delete cascade,
  avatar text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(name, family_id)
);

-- 8. Budget Expense Types
create table if not exists budget_expense_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 9. Import History
create table if not exists import_history (
  id bigint generated by default as identity primary key,
  file_name text not null,
  import_type text not null,
  record_count integer not null,
  import_date timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table expense_records enable row level security;
alter table expense_categories enable row level security;
alter table monthly_budgets enable row level security;
alter table year_goals enable row level security;
alter table expense_hierarchy enable row level security;
alter table families enable row level security;
alter table members enable row level security;
alter table budget_expense_types enable row level security;
alter table import_history enable row level security;

-- Create Policies (Public Access for now, as user requested "No Account" / simple setup)
-- In a real app with auth, we would check `auth.uid()`.
create policy "Enable all access" on expense_records for all using (true) with check (true);
create policy "Enable all access" on expense_categories for all using (true) with check (true);
create policy "Enable all access" on monthly_budgets for all using (true) with check (true);
create policy "Enable all access" on year_goals for all using (true) with check (true);
create policy "Enable all access" on expense_hierarchy for all using (true) with check (true);
create policy "Enable all access" on families for all using (true) with check (true);
create policy "Enable all access" on members for all using (true) with check (true);
create policy "Enable all access" on budget_expense_types for all using (true) with check (true);
create policy "Enable all access" on import_history for all using (true) with check (true);

-- Insert Default Data
insert into budget_expense_types (name) values ('常规费用'), ('固定费用') on conflict do nothing;

insert into expense_categories (name, icon, color) values 
('餐饮', '🍽️', '#EF4444'),
('交通', '🚗', '#3B82F6'),
('购物', '🛍️', '#8B5CF6'),
('娱乐', '🎬', '#F59E0B'),
('医疗', '🏥', '#10B981'),
('教育', '📚', '#6366F1'),
('住房', '🏠', '#EC4899'),
('其他', '📦', '#6B7280')
on conflict do nothing;

insert into families (name) values ('默认家庭组') on conflict do nothing;
-- Insert default member? Let's wait for app logic to handle it or insert one.
-- insert into members (name, family_id) select '我', id from families where name = '默认家庭组' on conflict do nothing;
